[package]
name = "zucchini"
description = "Blazing-fast TCP port scanner for Linux"
categories = ["security", "network-programming", "command-line-utilities"]
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
exclude.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
singsing-rs = { path = "../singsing-rs", version = "0.1.0" }

[lints]
workspace = true
