[package]
name = "singsing-rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "A blazing fast Linux IPv4 port scanning library"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["port-scanner", "tcp", "linux", "redteaming", "fast"]
categories = ["network-programming"]

[dependencies]
anyhow.workspace = true
ipnet.workspace = true
pnet.workspace = true

[lints]
workspace = true
