[package]
name = "singsing-rs"
description = "Blazing-fast IPv4/TCP port scanning library for Linux"
categories = ["security", "network-programming"]
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true
keywords.workspace = true
exclude.workspace = true

[dependencies]
ipnet.workspace = true
pnet.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true

[lints]
workspace = true
